[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci --prefix backend",
  "npm ci --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "npx --prefix backend prisma generate"
]

[start]
cmd = "node backend/src/server.js"
