[build]
builder = "NIXPACKS"
buildCommand = "npm install --prefix backend --legacy-peer-deps && npm install --prefix frontend --legacy-peer-deps && npm run build --prefix frontend && npx --prefix backend prisma generate"

[deploy]
startCommand = "node backend/src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
